apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoservicos.fullname" . }}-configmap
  labels:
    {{- include "geoservicos.labels" . | nindent 4 }}
data:
  default.conf: |-
    upstream mapproxy {
        server {{ include "mapproxy.fullname" .Subcharts.mapproxy }}:{{ .Values.mapproxy.service.port }};
    }

    {{ if .Values.mapserver.enabled -}}
    upstream mapserver {
        server {{ include "mapserver.fullname" .Subcharts.mapserver }}:{{ .Values.mapserver.service.port }};
    }
    {{- end }}

    # server {
    #     listen       {{ .Values.service.port }} default_server;
    #     server_name _;
    #     return 444;
    # }

    server {
        listen       {{ .Values.service.port }};
        server_name {{ range .Values.ingress.hosts }} {{ .host -}} {{ end }} {{ include "geoservicos.fullname" . }} localhost;
        server_tokens off;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # Mapproxy
        location /mapproxy {
            rewrite     /mapproxy/(.+) /$1 break;
            uwsgi_param SCRIPT_NAME /mapproxy;
            include     uwsgi_params;
            uwsgi_pass  mapproxy;
        }
        
        {{ if .Values.mapserver.enabled -}}
        # mapserver
        location /mapserver {
            rewrite     /mapserver/(.+) /$1 break;
            include     fastcgi_params;
            fastcgi_pass  mapserver;
        }
        {{- end }}
    }